name: super-linter
author: github
description: It is a simple combination on various linters, written in bash, to help validate your source code.
runs: 
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'check-square' 
  color: 'white'
